name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Get Time for BUILD_ID
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD_HHmm'

      - name: Get Branch name for BUILD_LABEL
        id: branch_name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Everything
        env:
          BUILD_ID: "${{ steps.time.outputs.time }}"
          BUILD_TYPE: "S"
          BUILD_LABEL: "CI ${{ steps.time.outputs.time }} (${{ steps.branch_name.outputs.branch }})"
        run: mvn package -Dtycho.disableP2Mirrors=true -DskipTests=true --batch-mode --strict-checksums --update-snapshots --show-version --no-transfer-progress

